version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
jobs:
  something:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - run:
          name: abc
          command: npx semantic-release
          filters:
            branches:
              only:
                - main

# Invoke jobs via workflows
workflows:
  build_deploy_master:
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.13'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - something
