version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
jobs:
  something:
    environment:
      DEF: $ABC
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      # - run:
      #     name: abc
      #     command: npx semantic-release
      #     filters:
      #       branches:
      #         only:
      #           - main
      - run:
          name: def
          command: |
            echo 'export DEPLOYMENT_TAG=abcd' >> $BASH_ENV
      - run: echo $DEPLOYMENT_TAG
      - run: echo $DEF
  someotherthing:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: abc
          command: echo $DEPLOYMENT_TAG
# Invoke jobs via workflows
workflows:
  build_deploy_master:
    jobs:
      - something
      - someotherthing
